import SwiftUI

// MARK: - Spoken / written "Hello World" greetings
//
// Every bubble is generated by picking a random programming language first,
// then a random greeting from this list to embed inside its print call.

private let spokenGreetings: [(language: String, text: String)] = [
    ("English",     "Hello, World!"),
    ("Spanish",     "¡Hola, Mundo!"),
    ("French",      "Bonjour, Monde !"),
    ("German",      "Hallo, Welt!"),
    ("Japanese",    "こんにちは、世界！"),
    ("Chinese",     "你好，世界！"),
    ("Arabic",      "مرحبًا بالعالم"),
    ("Russian",     "Привет, мир!"),
    ("Portuguese",  "Olá, Mundo!"),
    ("Italian",     "Ciao, Mondo!"),
    ("Korean",      "안녕하세요, 세계!"),
    ("Hindi",       "नमस्ते, दुनिया!"),
    ("Dutch",       "Hallo, Wereld!"),
    ("Swedish",     "Hej, Världen!"),
    ("Polish",      "Witaj, Świecie!"),
    ("Turkish",     "Merhaba, Dünya!"),
    ("Greek",       "Γεια σου, Κόσμε!"),
    ("Hebrew",      "!שלום עולם"),
    ("Thai",        "สวัสดีชาวโลก"),
    ("Vietnamese",  "Xin chào Thế giới"),
    ("Ukrainian",   "Привіт, Світ!"),
    ("Indonesian",  "Halo, Dunia!"),
    ("Swahili",     "Habari Dunia!"),
    ("Finnish",     "Hei, Maailma!"),
    ("Danish",      "Hej, Verden!"),
    ("Norwegian",   "Hei, Verden!"),
    ("Romanian",    "Bună ziua, Lume!"),
    ("Hungarian",   "Helló, Világ!"),
    ("Czech",       "Ahoj, Světe!"),
    ("Malay",       "Helo, Dunia!"),
    ("Tagalog",     "Kamusta, Mundo!"),
    ("Catalan",     "Hola, món!"),
    ("Welsh",       "Helo, Byd!"),
    ("Latin",       "Ave, Munde!"),
    ("Esperanto",   "Saluton, Mondo!"),
    ("Icelandic",   "Halló, heimur!"),
    ("Basque",      "Kaixo, mundua!"),
    ("Georgian",    "გამარჯობა, სამყარო!"),
    ("Armenian",    "Բարև ձեզ, Աշխարհ!"),
    ("Amharic",     "ሰላም ልዑል!"),
    ("Punjabi",     "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਦੁਨੀਆ!"),
    ("Urdu",        "!ہیلو، دنیا"),
    ("Bengali",     "হ্যালো, বিশ্ব!"),
    ("Tamil",       "வணக்கம், உலகம்!"),
    ("Gujarati",    "નમસ્તે, વિશ્વ!"),
    ("Slovenian",   "Pozdravljen, svet!"),
    ("Croatian",    "Pozdrav, Svijete!"),
    ("Serbian",     "Zdravo, Svete!"),
    ("Bulgarian",   "Здравей, свят!"),
    ("Macedonian",  "Здраво, свету!"),
    ("Mongolian",   "Сайн байна уу, дэлхий!"),
    ("Khmer",       "សួស្តីពិភពលោក"),
    ("Lao",         "ສະບາຍດີໂລກ"),
]

// MARK: - Programming-language print wrappers
//
// Selection: pick one of these at random, then pick a random spoken greeting
// above and wrap it — every bubble is always real code.

private typealias PrintWrapper = (String) -> String

private let printWrappers: [(lang: String, wrap: PrintWrapper)] = [
    ("Python",       { s in "print(\"\(s)\")" }),
    ("JavaScript",   { s in "console.log(\"\(s)\")" }),
    ("Swift",        { s in "print(\"\(s)\")" }),
    ("Java",         { s in "System.out.println(\"\(s)\");" }),
    ("C",            { s in "printf(\"\(s)\\n\");" }),
    ("C++",          { s in "std::cout << \"\(s)\";" }),
    ("Ruby",         { s in "puts \"\(s)\"" }),
    ("Go",           { s in "fmt.Println(\"\(s)\")" }),
    ("Rust",         { s in "println!(\"\(s)\");" }),
    ("PHP",          { s in "echo \"\(s)\";" }),
    ("Kotlin",       { s in "println(\"\(s)\")" }),
    ("TypeScript",   { s in "console.log(\"\(s)\")" }),
    ("Haskell",      { s in "putStrLn \"\(s)\"" }),
    ("Lua",          { s in "print(\"\(s)\")" }),
    ("Perl",         { s in "print \"\(s)\\n\";" }),
    ("R",            { s in "print(\"\(s)\")" }),
    ("Bash",         { s in "echo \"\(s)\"" }),
    ("PowerShell",   { s in "Write-Host \"\(s)\"" }),
    ("Elixir",       { s in "IO.puts \"\(s)\"" }),
    ("Clojure",      { s in "(println \"\(s)\")" }),
    ("Dart",         { s in "print('\(s)');" }),
    ("Julia",        { s in "println(\"\(s)\")" }),
    ("Nim",          { s in "echo \"\(s)\"" }),
    ("F#",           { s in "printfn \"\(s)\"" }),
    ("OCaml",        { s in "print_endline \"\(s)\"" }),
    ("Scala",        { s in "println(\"\(s)\")" }),
    ("Erlang",       { s in "io:format(\"\(s)~n\")." }),
    ("Groovy",       { s in "println \"\(s)\"" }),
    ("Objective-C",  { s in "NSLog(@\"\(s)\");" }),
    ("Crystal",      { s in "puts \"\(s)\"" }),
    ("Zig",          { s in "std.debug.print(\"\(s)\\n\", .{});" }),
    ("Ada",          { s in "Put_Line(\"\(s)\");" }),
    ("COBOL",        { s in "DISPLAY '\(s)'" }),
    ("Fortran",      { s in "WRITE(*,*) '\(s)'" }),
    ("Lisp",         { s in "(print \"\(s)\")" }),
    ("VB.NET",       { s in "Console.WriteLine(\"\(s)\")" }),
    ("MATLAB",       { s in "disp('\(s)')" }),
]

// MARK: - Floating bubble model

private struct FloatingBubble: Identifiable {
    let id:               UUID
    let displayLanguage:  String   // always the programming language name
    let displaySnippet:   String   // print call wrapping the spoken greeting
    let xFraction:        CGFloat
    let yFraction:        CGFloat
    let tailLeft:         Bool
    let rotation:         Double
    var opacity:          Double = 0
}

// MARK: - Tail shape

private struct BubbleTailShape: Shape {
    let pointsLeft: Bool

    func path(in rect: CGRect) -> Path {
        var p = Path()
        if pointsLeft {
            p.move(to:    CGPoint(x: rect.maxX, y: rect.minY))
            p.addLine(to: CGPoint(x: rect.minX, y: rect.maxY))
            p.addLine(to: CGPoint(x: rect.maxX, y: rect.maxY))
        } else {
            p.move(to:    CGPoint(x: rect.minX, y: rect.minY))
            p.addLine(to: CGPoint(x: rect.maxX, y: rect.maxY))
            p.addLine(to: CGPoint(x: rect.minX, y: rect.maxY))
        }
        p.closeSubpath()
        return p
    }
}

// MARK: - Single bubble cell

private struct BubbleCellView: View {
    let bubble: FloatingBubble

    private let bodyRadius:  CGFloat = 14
    private let sharpRadius: CGFloat = 3

    private var cornerRadii: RectangleCornerRadii {
        .init(
            topLeading:      bodyRadius,
            bottomLeading:   bubble.tailLeft ? sharpRadius : bodyRadius,
            bottomTrailing:  bubble.tailLeft ? bodyRadius  : sharpRadius,
            topTrailing:     bodyRadius
        )
    }

    var body: some View {
        ZStack(alignment: bubble.tailLeft ? .bottomLeading : .bottomTrailing) {
            VStack(alignment: .leading, spacing: 3) {
                Text(bubble.displayLanguage)
                    .font(.system(size: 8.5, weight: .semibold))
                    .foregroundStyle(.secondary)
                Text(bubble.displaySnippet)
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundStyle(.primary)
                    .lineLimit(3)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(.horizontal, 10)
            .padding(.vertical, 8)
            .frame(maxWidth: 210, alignment: .leading)
            .background(
                UnevenRoundedRectangle(cornerRadii: cornerRadii, style: .continuous)
                    .fill(.ultraThinMaterial)
                    .overlay(
                        UnevenRoundedRectangle(cornerRadii: cornerRadii, style: .continuous)
                            .strokeBorder(Color.primary.opacity(0.09), lineWidth: 0.5)
                    )
            )

            BubbleTailShape(pointsLeft: bubble.tailLeft)
                .fill(.ultraThinMaterial)
                .frame(width: 8, height: 11)
                .offset(x: bubble.tailLeft ? -5 : 5, y: 6)
        }
        .fixedSize()
        .rotationEffect(.degrees(bubble.rotation))
    }
}

// MARK: - Animated background

struct HelloWorldBackground: View {
    @State private var bubbles: [FloatingBubble] = []

    // Chosen once: how many bubbles to fill up to in the initial burst.
    private let initialTarget: Int = Int.random(in: 12...25)

    var body: some View {
        GeometryReader { geo in
            ZStack {
                ForEach(bubbles) { bubble in
                    BubbleCellView(bubble: bubble)
                        .position(
                            x: bubble.xFraction * geo.size.width,
                            y: bubble.yFraction * geo.size.height
                        )
                        .opacity(bubble.opacity)
                }
            }
            .task {
                // ── Phase 1: initial fill ──────────────────────────────
                // Spawn `initialTarget` bubbles with a short random stagger
                // between each so they drift in one by one rather than all
                // at once.  Read geo.size each iteration so we never lock
                // in a stale (or zero) size captured before layout finishes.
                var spawned = 0
                while spawned < initialTarget {
                    guard !Task.isCancelled else { return }
                    let size = geo.size
                    guard size.width > 0, size.height > 0 else {
                        // Geometry not ready yet — wait briefly and retry.
                        try? await Task.sleep(for: .milliseconds(50))
                        continue
                    }
                    spawnBubble(in: size)
                    spawned += 1
                    let stagger = Double.random(in: 0.25...0.9)
                    try? await Task.sleep(for: .seconds(stagger))
                }

                // ── Phase 2: maintenance trickle ───────────────────────
                // Keep spawning replacements as bubbles gradually fade out.
                // The cap inside spawnBubble prevents overflow.
                while !Task.isCancelled {
                    let interval = Double.random(in: 1.8...4.0)
                    try? await Task.sleep(for: .seconds(interval))
                    guard !Task.isCancelled else { return }
                    spawnBubble(in: geo.size)
                }
            }
        }
        .allowsHitTesting(false)
    }

    // MARK: - Spawn

    @MainActor
    private func spawnBubble(in size: CGSize) {
        guard size.width > 0, size.height > 0 else { return }
        guard bubbles.count < 25 else { return }

        // 1. Pick a random programming language.
        let wrapper  = printWrappers.randomElement()!
        // 2. Pick a random spoken/written greeting to embed inside it.
        let greeting = spokenGreetings.randomElement()!

        let id = UUID()

        let xPad = min(CGFloat(5), size.width  * 0.4)
        let yPad = min(CGFloat(5), size.height * 0.4)

        let bubble = FloatingBubble(
            id:              id,
            displayLanguage: wrapper.lang,
            displaySnippet:  wrapper.wrap(greeting.text),
            xFraction:       CGFloat.random(in: xPad / size.width  ... 1 - xPad / size.width),
            yFraction:       CGFloat.random(in: yPad / size.height ... 1 - yPad / size.height),
            tailLeft:        Bool.random(),
            rotation:        Double.random(in: -6...6)
        )

        bubbles.append(bubble)

        // Slow fade-in (varies per bubble for an organic feel).
        let fadeInDuration = Double.random(in: 1.8...3.5)
        withAnimation(.easeIn(duration: fadeInDuration)) {
            setOpacity(id, to: Double.random(in: 0.38...0.60))
        }

        // Each bubble lives for a long, individually random time before
        // starting to fade out, creating the effect where only a few are
        // disappearing at any given moment.
        let lifetime     = Double.random(in: 10.0...22.0)
        let fadeOutSpeed = Double.random(in: 2.5...6.0)   // random fade-out pace

        Task { @MainActor in
            try? await Task.sleep(for: .seconds(lifetime))
            withAnimation(.easeOut(duration: fadeOutSpeed)) {
                setOpacity(id, to: 0)
            }
            try? await Task.sleep(for: .seconds(fadeOutSpeed + 0.1))
            bubbles.removeAll { $0.id == id }
        }
    }

    // MARK: - Helpers

    private func setOpacity(_ id: UUID, to value: Double) {
        if let i = bubbles.firstIndex(where: { $0.id == id }) {
            bubbles[i].opacity = value
        }
    }
}
